
export type Locale="id"|"en";
export const dictionaries={
  en: {
    nav:{ stay:"Stay", experiences:"Experiences", dining:"Dining", offers:"Offers", gallery:"Gallery", story:"Story", location:"Location", about:"Story", villas:"Stay" },
    common:{ book:"BOOK", check_availability:"CHECK AVAILABILITY", explore:"EXPLORE", chat_concierge:"Chat Concierge", whatsapp:"WhatsApp", call:"Call" },
    home:{ hero_sub:"Uluwatu • Bali", hero_title:"Your private escape,\n surrounded by nature.", hero_desc:"A cliff retreat of four villas, two suites and a residence — composed for horizon, quiet and lingering light. Direct booking, concierge on WhatsApp.", badge:"★ 4.9 — 320 reviews", direct:"Direct booking benefits", intro_kicker:"The property", intro_title:"Architecture that\nframes the horizon.", story_cta:"OUR STORY —", stay:"Stay", view_all:"VIEW ALL STAY —", experiences:"Experiences", what_brings:"What brings you here?", dining:"Dining", dining_title:"Wood fire, ocean, long breakfast.", dining_desc:"Two venues — SERA on the cliff for fire and tasting menu, Bale Dauh for unhurried brunch under frangipani.", offers:"Offers", gallery:"Gallery", gallery_title:"Light, material, stillness.", location:"Location", location_title:"On the southernmost cliff\nof the island.", guest_notes:"Guest notes", begin:"Begin", plan_title:"Need help planning\nyour stay?", plan_desc:"Concierge on WhatsApp — itinerary, transfers, celebrations, sorted before you arrive." },
    stay:{ title:"Stay", desc:"Four villas, two suites and a residence. Each placed for privacy, each framed for horizon.", from:"FROM", per_night:"per night", not_sure:"Not sure? Concierge will match you in 2 minutes.", check_dates:"CHECK DATES", detail_from:"From", ask:"Ask Concierge", related:"Related", included:"What's Included", policies:"Policies", amenities:"Amenities" },
    booking:{ title:"Check availability", step1:"1 Dates & Guests", step2:"2 Details", step3:"3 Confirmation", checkin:"Check-in *", checkout:"Check-out *", adults:"Adults", children:"Children", stay:"Stay", addons:"Add-ons", check_btn:"CHECK AVAILABILITY", summary:"Summary", nights:"Nights", rate:"Rate", subtotal:"Subtotal", total:"Total", guest_details:"Guest details", name:"Full name *", email:"Email *", phone:"Phone / WhatsApp", request:"Special requests", back:"BACK", confirm:"CONFIRM REQUEST", review:"Review", success_title:"Booking request received", success_desc:"We have your request", pay_midtrans:"PAY WITH MIDTRANS — Snap", back_home:"BACK HOME", need_login:"Please login to continue booking", login_cta:"LOGIN TO BOOK" },
    auth:{ welcome:"Welcome back", demo:"Demo: admin@aura.bali / Admin123! — or use Google login", email:"Email", password:"Password", signin:"Sign in with Email", google:"Continue with Google", no_account:"No account?", register:"Register", create:"Create account", name:"Name", confirm:"Confirm *", already:"Already have account?", login:"Login", weak:"Password too weak" },
    contact:{ title:"Concierge", desc:"WhatsApp is fastest. Or leave a note — we reply within an hour, 07:00–23:00 WITA.", phone:"Phone", email:"Email", subject:"Subject", message:"Message *", send:"SEND MESSAGE", sending:"SENDING…", sent:"Message sent — we will reply shortly.", required:"Please fill name, email and message." },
    faq:{ title:"FAQ", help:"Help" },
    footer:{ explore:"Explore", information:"Information", contact:"Contact", rights:"All rights reserved." },
    admin:{ title:"Dashboard", signin_as:"Signed in as", bookings:"Bookings", properties:"Properties", recent:"Recent bookings", no_bookings:"No bookings yet", sales:"Sales", occupancy:"Occupancy", guests:"Guests", performance:"Performance", today:"Today", last7:"Last 7 days", last30:"Last 30 days", month:"This month", export:"Export", export_csv:"Export CSV", export_pdf:"Export PDF" }
  },
  id: {
    nav:{ stay:"Menginap", experiences:"Pengalaman", dining:"Kuliner", offers:"Penawaran", gallery:"Galeri", story:"Cerita", location:"Lokasi", about:"Cerita", villas:"Menginap" },
    common:{ book:"PESAN", check_availability:"CEK KETERSEDIAAN", explore:"JELAJAHI", chat_concierge:"Chat Concierge", whatsapp:"WhatsApp", call:"Telepon" },
    home:{ hero_sub:"Uluwatu • Bali", hero_title:"Pelarian privat Anda,\ndikelilingi alam.", hero_desc:"Retret tebing dengan empat villa, dua suite dan satu residence — dirancang untuk horizon, keheningan dan cahaya. Booking langsung, concierge via WhatsApp.", badge:"★ 4.9 — 320 ulasan", direct:"Keuntungan booking langsung", intro_kicker:"Properti", intro_title:"Arsitektur yang\nmembingkai horizon.", story_cta:"CERITA KAMI —", stay:"Menginap", view_all:"LIHAT SEMUA —", experiences:"Pengalaman", what_brings:"Apa yang membawa Anda ke sini?", dining:"Kuliner", dining_title:"Api kayu, laut, sarapan panjang.", dining_desc:"Dua venue — SERA di tebing untuk fire & tasting menu, Bale Dauh untuk brunch santai di bawah frangipani.", offers:"Penawaran", gallery:"Galeri", gallery_title:"Cahaya, material, keheningan.", location:"Lokasi", location_title:"Di tebing paling selatan\npulau.", guest_notes:"Catatan tamu", begin:"Mulai", plan_title:"Butuh bantuan merencanakan\nmenginap?", plan_desc:"Concierge di WhatsApp — itinerary, transfer, perayaan, beres sebelum tiba." },
    stay:{ title:"Menginap", desc:"Empat villa, dua suite dan satu residence. Masing-masing untuk privasi, masing-masing membingkai horizon.", from:"MULAI", per_night:"per malam", not_sure:"Ragu? Concierge akan mencocokkan dalam 2 menit.", check_dates:"CEK TANGGAL", detail_from:"Mulai", ask:"Tanya Concierge", related:"Terkait", included:"Termasuk", policies:"Kebijakan", amenities:"Fasilitas" },
    booking:{ title:"Cek ketersediaan", step1:"1 Tanggal & Tamu", step2:"2 Detail", step3:"3 Konfirmasi", checkin:"Check-in *", checkout:"Check-out *", adults:"Dewasa", children:"Anak", stay:"Menginap", addons:"Add-on", check_btn:"CEK KETERSEDIAAN", summary:"Ringkasan", nights:"Malam", rate:"Tarif", subtotal:"Subtotal", total:"Total", guest_details:"Detail tamu", name:"Nama lengkap *", email:"Email *", phone:"Telepon / WhatsApp", request:"Permintaan khusus", back:"KEMBALI", confirm:"KONFIRMASI", review:"Ulasan", success_title:"Permintaan booking diterima", success_desc:"Kami menerima permintaan Anda", pay_midtrans:"BAYAR DENGAN MIDTRANS — Snap", back_home:"KEMBALI", need_login:"Silakan login untuk melanjutkan booking", login_cta:"LOGIN UNTUK PESAN" },
    auth:{ welcome:"Selamat datang kembali", demo:"Demo: admin@aura.bali / Admin123! — atau login Google", email:"Email", password:"Password", signin:"Masuk dengan Email", google:"Lanjut dengan Google", no_account:"Belum punya akun?", register:"Daftar", create:"Buat akun", name:"Nama", confirm:"Konfirmasi *", already:"Sudah punya akun?", login:"Masuk", weak:"Password terlalu lemah" },
    contact:{ title:"Concierge", desc:"WhatsApp paling cepat. Atau tinggalkan pesan — kami balas dalam satu jam, 07:00–23:00 WITA.", phone:"Telepon", email:"Email", subject:"Subjek", message:"Pesan *", send:"KIRIM PESAN", sending:"MENGIRIM…", sent:"Pesan terkirim — kami akan segera balas.", required:"Isi nama, email dan pesan." },
    faq:{ title:"FAQ", help:"Bantuan" },
    footer:{ explore:"Jelajahi", information:"Informasi", contact:"Kontak", rights:"Hak cipta dilindungi." },
    admin:{ title:"Dashboard", signin_as:"Masuk sebagai", bookings:"Booking", properties:"Properti", recent:"Booking terbaru", no_bookings:"Belum ada booking", sales:"Penjualan", occupancy:"Okupansi", guests:"Tamu", performance:"Performa", today:"Hari ini", last7:"7 hari terakhir", last30:"30 hari terakhir", month:"Bulan ini", export:"Ekspor", export_csv:"Ekspor CSV", export_pdf:"Ekspor PDF" }
  }
};
export function getDictionary(locale:Locale){ return dictionaries[locale]||dictionaries.en; }
